### ISSUE TITLE
log is overlapping  

### ISSUE THREAD

**Issue by chintan9** [FormidableLabs/webpack-dashboard#109] opened 2016-09-01 05:56 UTC
> Please provide a description of the bug / issue, and provide the details below:
# log is overlapping  
###### If the issue is visual, please provide screenshots here

<img width="997" alt="screen shot 2016-09-01 at 12 45 40 am" src="https://cloud.githubusercontent.com/assets/1642564/18156673/936cbe3e-6fdd-11e6-81fb-b2889af2057f.png">
# 
###### Steps to reproduce the problem

https://github.com/chintan9/react-redux-starter-kit

run your project 
make changes
get errors
# 
###### Please provide a gist of relevant files
1. package.json (specifically the script you are using to start the dashboard) 

```
{
    "name": "react-redux-starter-kit",
    "version": "3.0.0-alpha.2",
    "description": "Get started with React, Redux, and React-Router!",
    "main": "index.js",
    "engines": {
        "node": ">=4.2.0",
        "npm": "^3.0.0"
    },
    "scripts": {
        "clean": "rimraf dist",
        "compile": "better-npm-run compile",
        "lint": "eslint src tests server",
        "lint:fix": "npm run lint -- --fix",
        "start": "better-npm-run start",
        "dev": "better-npm-run dev",
        "dev:no-debug": "npm run dev -- --no_debug",
        "test": "better-npm-run test",
        "test:dev": "npm run test -- --watch",
        "deploy": "better-npm-run deploy",
        "deploy:dev": "better-npm-run deploy:dev",
        "deploy:prod": "better-npm-run deploy:prod",
        "codecov": "cat coverage/*/lcov.info | codecov"
    },
    "betterScripts": {
        "compile": {
            "command": "babel-node bin/compile",
            "env": {
                "DEBUG": "app:*"
            }
        },
        "dev": {
            "command": "nodemon --exec babel-node bin/server",
            "env": {
                "NODE_ENV": "development",
                "DEBUG": "app:*"
            }
        },
        "deploy": {
            "command": "npm run clean && npm run compile",
            "env": {
                "DEBUG": "app:*"
            }
        },
        "deploy:dev": {
            "command": "npm run deploy",
            "env": {
                "NODE_ENV": "development",
                "DEBUG": "app:*"
            }
        },
        "deploy:prod": {
            "command": "npm run deploy",
            "env": {
                "NODE_ENV": "production",
                "DEBUG": "app:*"
            }
        },
        "start": {
            "command": "babel-node bin/server",
            "env": {
                "DEBUG": "app:*"
            }
        },
        "test": {
            "command": "babel-node ./node_modules/karma/bin/karma start build/karma.conf",
            "env": {
                "NODE_ENV": "test",
                "DEBUG": "app:*"
            }
        }
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/davezuko/react-redux-starter-kit.git"
    },
    "author": "David Zukowski <david@zuko.me> (http://zuko.me)",
    "license": "MIT",
    "dependencies": {
        "babel-cli": "^6.5.1",
        "babel-core": "^6.3.17",
        "babel-loader": "^6.2.0",
        "babel-plugin-transform-runtime": "^6.3.13",
        "babel-polyfill": "^6.9.0",
        "babel-preset-es2015": "^6.3.13",
        "babel-preset-react": "^6.3.13",
        "babel-preset-stage-0": "^6.3.13",
        "babel-register": "^6.3.13",
        "babel-runtime": "^6.3.19",
        "better-npm-run": "0.0.11",
        "css-loader": "^0.24.0",
        "cssnano": "^3.3.2",
        "debug": "^2.2.0",
        "extract-text-webpack-plugin": "^1.0.0",
        "file-loader": "^0.9.0",
        "fs-extra": "^0.30.0",
        "history": "^2",
        "html-webpack-plugin": "^2.7.1",
        "imports-loader": "^0.6.5",
        "ip": "^1.1.2",
        "json-loader": "^0.5.4",
        "koa": "^2.0.0-alpha.3",
        "koa-connect-history-api-fallback": "^0.3.0",
        "koa-convert": "^1.2.0",
        "koa-proxy": "^0.6.0",
        "koa-static": "^3.0.0",
        "node-sass": "^3.7.0",
        "normalize.css": "^4.1.1",
        "postcss-loader": "^0.11.0",
        "react": "^15.0.0",
        "react-dom": "^15.0.0",
        "react-redux": "^4.0.0",
        "react-router": "^2.2.0",
        "react-router-redux": "^4.0.0",
        "redux": "^3.0.0",
        "redux-thunk": "^2.0.0",
        "rimraf": "^2.5.1",
        "sass-loader": "^4.0.0",
        "style-loader": "^0.13.0",
        "url-loader": "^0.5.6",
        "webpack": "^1.12.14",
        "yargs": "^5.0.0"
    },
    "devDependencies": {
        "babel-eslint": "^6.0.0-beta.6",
        "chai": "^3.4.1",
        "chai-as-promised": "^5.1.0",
        "chai-enzyme": "^0.5.0",
        "cheerio": "^0.20.0",
        "codecov": "^1.0.1",
        "enzyme": "^2.0.0",
        "eslint": "^3.0.1",
        "eslint-config-standard": "^6.0.0",
        "eslint-config-standard-react": "^4.0.0",
        "eslint-plugin-babel": "^3.2.0",
        "eslint-plugin-promise": "^2.0.0",
        "eslint-plugin-react": "^6.0.0",
        "eslint-plugin-standard": "^2.0.0",
        "isparta-loader": "^2.0.0",
        "karma": "^1.0.0",
        "karma-coverage": "^1.0.0",
        "karma-mocha": "^1.0.1",
        "karma-mocha-reporter": "^2.0.0",
        "karma-phantomjs-launcher": "^1.0.0",
        "karma-webpack-with-fast-source-maps": "^1.9.2",
        "mocha": "^3.0.1",
        "nodemon": "^1.8.1",
        "phantomjs-prebuilt": "^2.1.3",
        "react-addons-test-utils": "^15.0.0",
        "redbox-react": "^1.2.10",
        "sinon": "^1.17.3",
        "sinon-chai": "^2.8.0",
        "webpack-dashboard": "^0.1.8",
        "webpack-dev-middleware": "^1.6.1",
        "webpack-hot-middleware": "^2.6.0"
    }
} 
```
1. webpack.config.js

```
import webpack from 'webpack'
import cssnano from 'cssnano'
import HtmlWebpackPlugin from 'html-webpack-plugin'
import Dashboard from 'webpack-dashboard'
import DashboardPlugin from 'webpack-dashboard/plugin'
import ExtractTextPlugin from 'extract-text-webpack-plugin'
import config from '../config'
import _debug from 'debug'

const debug = _debug('app:webpack:config')
const paths = config.utils_paths
const { __DEV__, __PROD__, __TEST__ } = config.globals
const dashboard = new Dashboard();

debug('Create configuration.')
const webpackConfig = {
        name: 'client',
        target: 'web',
        devtool: config.compiler_devtool,
        resolve: {
            root: paths.client(),
            extensions: ['', '.js', '.jsx', '.json']
        },
        module: {}
    }
    // ------------------------------------
    // Entry Points
    // ------------------------------------
const APP_ENTRY_PATHS = [
    paths.client('main.js')
]

webpackConfig.entry = {
    app: __DEV__ ? APP_ENTRY_PATHS.concat(`webpack-hot-middleware/client?path=${config.compiler_public_path}__webpack_hmr`) : APP_ENTRY_PATHS,
    vendor: config.compiler_vendor
}

// ------------------------------------
// Bundle Output
// ------------------------------------
webpackConfig.output = {
    filename: `[name].[${config.compiler_hash_type}].js`,
    path: paths.dist(),
    publicPath: config.compiler_public_path
}

// ------------------------------------
// Plugins
// ------------------------------------
webpackConfig.plugins = [
    new webpack.DefinePlugin(config.globals),
    new HtmlWebpackPlugin({
        template: paths.client('index.html'),
        hash: false,
        favicon: paths.client('static/favicon.ico'),
        filename: 'index.html',
        inject: 'body',
        minify: {
            collapseWhitespace: true
        }
    })
]

if (__DEV__) {
    debug('Enable plugins for live development (HMR, NoErrors).')
    webpackConfig.plugins.push(
        new webpack.HotModuleReplacementPlugin(),
        new DashboardPlugin(dashboard.setData),
        new webpack.NoErrorsPlugin()
    )
} else if (__PROD__) {
    debug('Enable plugins for production (OccurenceOrder, Dedupe & UglifyJS).')
    webpackConfig.plugins.push(
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                unused: true,
                dead_code: true,
                warnings: false
            }
        })
    )
}

// Don't split bundles during testing, since we only want import one bundle
if (!__TEST__) {
    webpackConfig.plugins.push(
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendor']
        })
    )
}

// ------------------------------------
// Pre-Loaders
// ------------------------------------
/*
[ NOTE ]
We no longer use eslint-loader due to it severely impacting build
times for larger projects. `npm run lint` still exists to aid in
deploy processes (such as with CI), and it's recommended that you
use a linting plugin for your IDE in place of this loader.

If you do wish to continue using the loader, you can uncomment
the code below and run `npm i --save-dev eslint-loader`. This code
will be removed in a future release.

webpackConfig.module.preLoaders = [{
  test: /\.(js|jsx)$/,
  loader: 'eslint',
  exclude: /node_modules/
}]

webpackConfig.eslint = {
  configFile: paths.base('.eslintrc'),
  emitWarning: __DEV__
}
*/

// ------------------------------------
// Loaders
// ------------------------------------
// JavaScript / JSON
webpackConfig.module.loaders = [{
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    loader: 'babel',
    query: {
        cacheDirectory: true,
        plugins: ['transform-runtime'],
        presets: ['es2015', 'react', 'stage-0']
    }
}, {
    test: /\.json$/,
    loader: 'json'
}]

// ------------------------------------
// Style Loaders
// ------------------------------------
// We use cssnano with the postcss loader, so we tell
// css-loader not to duplicate minimization.
const BASE_CSS_LOADER = 'css?sourceMap&-minimize'

// Add any packge names here whose styles need to be treated as CSS modules.
// These paths will be combined into a single regex.
const PATHS_TO_TREAT_AS_CSS_MODULES = [
    // 'react-toolbox', (example)
]

// If config has CSS modules enabled, treat this project's styles as CSS modules.
if (config.compiler_css_modules) {
    PATHS_TO_TREAT_AS_CSS_MODULES.push(
        paths.client().replace(/[\^\$\.\*\+\-\?\=\!\:\|\\\/\(\)\[\]\{\}\,]/g, '\\$&') // eslint-disable-line
    )
}

const isUsingCSSModules = !!PATHS_TO_TREAT_AS_CSS_MODULES.length
const cssModulesRegex = new RegExp(`(${PATHS_TO_TREAT_AS_CSS_MODULES.join('|')})`)

// Loaders for styles that need to be treated as CSS modules.
if (isUsingCSSModules) {
    const cssModulesLoader = [
        BASE_CSS_LOADER,
        'modules',
        'importLoaders=1',
        'localIdentName=[name]__[local]___[hash:base64:5]'
    ].join('&')

    webpackConfig.module.loaders.push({
        test: /\.scss$/,
        include: cssModulesRegex,
        loaders: [
            'style',
            cssModulesLoader,
            'postcss',
            'sass?sourceMap'
        ]
    })

    webpackConfig.module.loaders.push({
        test: /\.css$/,
        include: cssModulesRegex,
        loaders: [
            'style',
            cssModulesLoader,
            'postcss'
        ]
    })
}

// Loaders for files that should not be treated as CSS modules.
const excludeCSSModules = isUsingCSSModules ? cssModulesRegex : false
webpackConfig.module.loaders.push({
    test: /\.scss$/,
    exclude: excludeCSSModules,
    loaders: [
        'style',
        BASE_CSS_LOADER,
        'postcss',
        'sass?sourceMap'
    ]
})
webpackConfig.module.loaders.push({
    test: /\.css$/,
    exclude: excludeCSSModules,
    loaders: [
        'style',
        BASE_CSS_LOADER,
        'postcss'
    ]
})

// ------------------------------------
// Style Configuration
// ------------------------------------
webpackConfig.sassLoader = {
    includePaths: paths.client('styles')
}

webpackConfig.postcss = [
    cssnano({
        autoprefixer: {
            add: true,
            remove: true,
            browsers: ['last 2 versions']
        },
        discardComments: {
            removeAll: true
        },
        discardUnused: false,
        mergeIdents: false,
        reduceIdents: false,
        safe: true,
        sourcemap: true
    })
]

// File loaders
/* eslint-disable */
webpackConfig.module.loaders.push({ test: /\.woff(\?.*)?$/, loader: 'url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff' }, { test: /\.woff2(\?.*)?$/, loader: 'url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff2' }, { test: /\.otf(\?.*)?$/, loader: 'file?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=font/opentype' }, { test: /\.ttf(\?.*)?$/, loader: 'url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/octet-stream' }, { test: /\.eot(\?.*)?$/, loader: 'file?prefix=fonts/&name=[path][name].[ext]' }, { test: /\.svg(\?.*)?$/, loader: 'url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=image/svg+xml' }, { test: /\.(png|jpg)$/, loader: 'url?limit=8192' })
    /* eslint-enable */

// ------------------------------------
// Finalize Configuration
// ------------------------------------
// when we don't know the public path (we know it only when HMR is enabled [in development]) we
// need to use the extractTextPlugin to fix this issue:
// http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts/34133809#34133809
if (!__DEV__) {
    debug('Apply ExtractTextPlugin to CSS loaders.')
    webpackConfig.module.loaders.filter((loader) =>
        loader.loaders && loader.loaders.find((name) => /css/.test(name.split('?')[0]))
    ).forEach((loader) => {
        const [first, ...rest] = loader.loaders
        loader.loader = ExtractTextPlugin.extract(first, rest.join('!'))
        Reflect.deleteProperty(loader, 'loaders')
    })

    webpackConfig.plugins.push(
        new ExtractTextPlugin('[name].[contenthash].css', {
            allChunks: true
        })
    )
}

export default webpackConfig
```
1. index.js (Your express based dev server, if applicable)
   `webpack-dev.js`

```
import WebpackDevMiddleware from 'webpack-dev-middleware'
import applyExpressMiddleware from '../lib/apply-express-middleware'
import Dashboard from 'webpack-dashboard'
import DashboardPlugin from 'webpack-dashboard/plugin'
import _debug from 'debug'
import config from '../../config'

const paths = config.utils_paths
const debug = _debug('app:server:webpack-dev')

export default function (compiler, publicPath) {
  debug('Enable webpack dev middleware.')

  const middleware = WebpackDevMiddleware(compiler, {
    publicPath,
    contentBase: paths.client(),
    hot: true,
    log: () => {},
    quiet: true,
    noInfo: config.compiler_quiet,
    lazy: false,
    stats: config.compiler_stats
  })

  return async function koaWebpackDevMiddleware (ctx, next) {
    let hasNext = await applyExpressMiddleware(middleware, ctx.req, {
      end: (content) => (ctx.body = content),
      setHeader: function () {
        ctx.set.apply(ctx, arguments)
      }
    })

    if (hasNext) {
      await next()
    }
  }
}

```
# 
###### More Details
- What operating system are you on? osx
- What terminal application are you using? terminal.app
- What version of webpack-dashboard are you using? 0.18
- What is the output of running `echo $TERM`? xterm-256color

**Comment by augbog** [comment] 2016-09-02 22:27
Confirming I see this issue as well

**Comment by kenwheeler** [comment] 2016-09-06 10:07
Can you try setting it up the new way, where you use the webpack-dashboard bin instead of creating an instance in your config?

**Comment by neutraali** [comment] 2016-09-06 12:45
Same issue... Win10 KiTTY -terminal by using Webpack Dashboard "the old way" via webpack-dev-server config without an express server. We're running it via gulp, and a separate task is updating styles in the background. Some of that output seems to spill over Webpack Dashboard in an ugly fashion. Would be better if the dashboard captured all output into the log window when it is running.

![webpack-dashboard](https://cloud.githubusercontent.com/assets/16540190/18273954/af6eb140-7448-11e6-8761-74e4f4c252ba.png)

**Comment by augbog** [comment] 2016-09-08 20:53
I'm pretty sure this is an issue with `webpack-hot-middleware` which doesn't know how to parse the `dashboard.setData` when we feed the compiler in after we have applied the dashboard changes.

```
const compiler = webpack(config);
const dashboard = new Dashboard();

compiler.apply(new DashboardPlugin(dashboard.setData));
app.use(webpackMiddleware);
app.use(webpackHotMiddleware(compiler));
```

I tried the `webpack-dashboard` bin command and without calling `compiler.apply` it doesn't have the log overlap but naturally nothing gets fed into the dashboard other than in the log output. When I call both, I get this (most likely because its try to run it twice)

<img width="1028" alt="screen shot 2016-09-08 at 1 48 42 pm" src="https://cloud.githubusercontent.com/assets/2054339/18366425/75c37668-75cb-11e6-849c-8c0b8e41ef05.png">

**Comment by clementprevot** [comment] 2016-09-13 13:32
Same problem here.

If I use the binary, the logs are correctly displaying but I have no other data fed into the dashboard and the hot reloading isn't working.
If I use the old way, everything is working fine except the logs that are overlapping

**Comment by icd2k3** [comment] 2016-10-14 18:59
Same issue here as well - I'm running karma in the background hoping it would output to the dashboard console, but no dice.

Here's an example of what I'm seeing. https://cl.ly/3D1n3s3b2Q2g . Has anyone found a good workaround yet?

**Comment by rovansteen** [comment] 2016-10-26 12:42
I'm having this issue as well. I can't use the bin because I want to supply the ports that are used by webpack-dashboard based on an .env file with `dotenv`. Any workarounds for this?

**Comment by pribilinskiy** [comment] 2017-01-16 09:34
Same problem when running in a VirtualBox machine through `ssh`. I had similar problems with `terminal-menu` but solved with following code:
```
menu.on('close', function() {
	process.stdin.setRawMode(false);
	process.stdin.end();
}
```

**Comment by chintan9** [comment] 2017-01-16 15:06
Could you tell more about. Where do I add this code.

**Comment by pribilinskiy** [comment] 2017-01-26 07:42
That code was added to `terminal-menu` and may not be applicable to `webpack-dashboard`

**Comment by chintan9** [comment] 2017-01-31 23:00
@icd2k3  Can give your solution for this work around.

**Comment by icd2k3** [comment] 2017-02-13 00:50
@chintan9 my workaround is detailed in my post. I couldn't get it working WITHIN webpack-dashboard so I use ttab to automatically open 2 tabs (1 for webpack-dashboard and the other for my test runner)

**Comment by hirtie-maxim** [comment] 2017-03-20 13:08
For me worked not using dashboard.setData manually, like this:
```
var Dashboard = require('webpack-dashboard');
var DashboardPlugin = require('webpack-dashboard/plugin');
var dashboard = new Dashboard();

plugins: [
    new DashboardPlugin(dashboard.setData)
  ]
```
But only:
```
plugins: [
    new DashboardPlugin()
  ]
```

And then run ```webpack-dashboard -- webpack-dev-server --hot --quiet```

The hot reloading is working alongside with showing of data in dashboard.

**Comment by ryan-roemer** [comment] 2017-11-07 19:03
Can folks experience this issue upgrade to `^1.0.1` and try again / report back?

If the issue persists, can someone create an updated minimal repository with install + reproduction steps so that we can jump in and more quickly figure out what's going on? Thanks!

**Comment by ryan-roemer** [comment] 2017-11-14 21:30
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!

**Closed by ryan-roemer** 2017-11-14 21:30 UTC
Labels: Unverified

**Comment by neutraali** [comment] 2017-11-16 09:54
This issue is still very much alive to this day. It's reproducible by running an async task in the backround with a bit of delay and outputting something via `console.log`.

However there are currently other, more critical issues like #182 that are preventing the use of `webpack-dashboard` entirely.

**Comment by ryan-roemer** [comment] 2017-11-16 14:51
@neutraali -- As I mentioned on your other comment, we'll need a minimal repository to be able to effectively see what's going on. Feel free to open both a new issue with that repository and also paste it in a comment here if it also applies to this issue.
