### ISSUE TITLE
Operation field output seems to wrap over log area

### ISSUE THREAD

**Issue by kbjr** [FormidableLabs/webpack-dashboard#23] opened 2016-08-15 19:55 UTC
Looks like any long output in the operation field wraps around the edge of the screen and covers over the log area.

Windows 7, Powershell running in Cmder.

![image](https://cloud.githubusercontent.com/assets/195127/17677313/1f819e98-62e7-11e6-8763-638029ce4473.png)

**Comment by kenwheeler** [comment] 2016-08-15 19:56
This appears to be a dupe of #12 , going to get this sorted out tonight.

**Closed by kenwheeler** 2016-08-15 19:56 UTC
