### ISSUE TITLE
npm run build fail to build dist folder

### ISSUE THREAD

**Issue by bvscsai** [FormidableLabs/webpack-dashboard#190] opened 2017-09-05 09:05 UTC
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! app@0.0.0 build: `rimraf dist && webpack --progress --profile --bail`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the app@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-05T09_02_05_917Z-debug.log

**Comment by ryan-roemer** [comment] 2017-09-05 22:15
Duplicate of https://github.com/FormidableLabs/webpack-dashboard/issues/187

**Closed by ryan-roemer** 2017-09-05 22:15 UTC
