### ISSUE TITLE
webpack-dashboard can't run script in shelljs

### ISSUE THREAD

**Issue by Roxyhuang** [FormidableLabs/webpack-dashboard#214] opened 2017-10-25 07:22 UTC
====================================================================

###### If the issue is visual, please provide screenshots here
in iTerm2 will be show some messy code

```
Cf0Ce0Cd0Cc0Cb0Ca0C`0C^0C]0C\0CZ0CY0CX0CW0CW1CV1CU1CT1CS1CR1CQ1CP1CO1CN1CL2CK2CJ2CI2CH2CF2CE2CD2CC2CB2CA2C@2C?
```

====================================================================

###### Steps to reproduce the problem

1. start run script in package.json  for script file 
2. run dashboard in javascript file by shell.js
3. show some messy code

====================================================================

###### Please provide a gist of relevant files

minimal repository : https://github.com/Roxyhuang/dashboard-shell-error.git

====================================================================

###### More Details

OS X 10.12.5 
iTerm2
"webpack-dashboard": "1.0.0-5"
"webpack": "3.6.0",
"shelljs": "0.7.8",

**Comment by ryan-roemer** [comment] 2017-10-25 18:42
Can you provide a minimal repository with install / reproduction steps to see the error? This will greatly aid our efforts at figuring out what's going on. Thanks!

**Comment by Roxyhuang** [comment] 2017-10-27 02:51
You can clone the repository:
https://github.com/Roxyhuang/dashboard-shell-error.git

Please use 

npm run dev

Thank you very much!!!

**Comment by ryan-roemer** [comment] 2017-10-30 18:47
I do see the behavior you've noted in your repository -- thanks!

However, looking at these issues:

- https://github.com/shelljs/shelljs/issues/186
- https://github.com/shelljs/shelljs/issues/86
- https://github.com/shelljs/shelljs/issues/242

... it seems like `shelljs` just doesn't support full terminal features like colors, and presumably all of the cursor magic for a full-fledged library like `blessed`.

Is `shelljs` supposed to support `blessed` and `blessed`-based applications?

**Comment by ryan-roemer** [comment] 2017-10-30 18:59
Confirm. `shelljs` is incompatible with `blessed`. I took the absolute simplest blessed example app and ran it in your setup with this diff:

```diff
diff --git a/bin/commands.js b/bin/commands.js
index 0a7fd66..500498f 100644
--- a/bin/commands.js
+++ b/bin/commands.js
@@ -6,6 +6,7 @@ const option = process.argv[2];
 switch (option) {
     case 'dev':
       console.log(chalk.green('building for development...'));
-      shell.exec('webpack-dashboard -p 3300 -c blue -t dashboard -- babel-node script/dev-server.js dev');
+      shell.exec('node node_modules/blessed/example/simple-form.js');
+      //shell.exec('webpack-dashboard -p 3300 -c blue -t dashboard -- babel-node script/dev-server.js dev');
       break;
 }
diff --git a/package.json b/package.json
index 82b59af..f0b8893 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,10 @@
     "not ie < 9"
   ],
   "dependencies": {
-    "shelljs": "^0.7.8"
+    "blessed": "^0.1.81",
+    "pty.js": "^0.3.1",
+    "shelljs": "^0.7.8",
+    "term.js": "^0.0.7"
   },
   "devDependencies": {
     "babel": "^6.23.0",
```

and I got the exact same gibberish output spewing throughout the console.

I'm going to close this issue as it's not something specific to `webpack-dashboard`, but rather to `shelljs`'s presumable handling of complex terminal output. Feel free to add a doc PR here if you'd like to call out shelljs' issues and if you'd like cc me on any issues you open up on `shelljs` and/or `blessed` to address the root cause so I can track it and eventually see if that combination will get support that we could document here on the dashboard.

Thanks!

**Closed by ryan-roemer** 2017-10-30 18:59 UTC
Labels: Unverified
