### ISSUE TITLE
Mouse events captured after exiting dev server

### ISSUE THREAD

**Issue by grgur** [FormidableLabs/webpack-dashboard#34] opened 2016-08-16 07:55 UTC
Great work on the dashboard, guys!

Just tried it out on a project I've been working on, but ran into an issue. Looks like mouse events are still being captured after closing the server (used Ctrl+C as usual).

This is what it looks like as I move the mouse over the window:
![](http://f.grgur.com/ETsR5NshON.png)

Using
* iTerm2 build 3.0.5
* Webpack 1.13.1

Cheers

**Comment by isaachinman** [comment] 2016-08-16 12:16
I have encountered this problem too. Project looks really cool but this is annoying enough to prevent me using it.

**Comment by kenwheeler** [comment] 2016-08-16 12:27
This is so weird. I wish I could reproduce. Are there any other env variables at play?

**Comment by kenwheeler** [comment] 2016-08-16 12:29
What kind of computer? What version OS? Are you using a force touch trackpad?

**Comment by kenwheeler** [comment] 2016-08-16 12:31
Oh wait, is your terminal in utf-8 mode?

**Comment by viniciusdacal** [comment] 2016-08-16 12:37
I'm having the same problem.
OS X El Capitan 10.11.1

![captura de tela 2016-08-16 as 09 31 46](https://cloud.githubusercontent.com/assets/2660570/17699006/a7ba861e-6394-11e6-8781-123d9403a7a9.png)

Indeed, here the encoding is utf-8

**Comment by kenwheeler** [comment] 2016-08-16 12:45
Can I see a gist of someones entire config? I want to see how you are running this, your webpack/server config and what $TERM returns. If i hook into stdout I can see those characters on mouse move, but it looks like your setup is outputting that by default.

**Comment by kenwheeler** [comment] 2016-08-16 12:57
Are you running nodemon?

**Comment by brandonmp** [comment] 2016-08-16 13:07
[here's a gist](https://gist.github.com/brandonmp/ac6670826146a0dfb876955260841a1d) w/ my relevant config files (and then some)

not running `nodemon` afaik

**Comment by kenwheeler** [comment] 2016-08-16 13:09
@brandonmp how are you running main.js?

**Comment by kenwheeler** [comment] 2016-08-16 13:15
This is definitely nodemon, gonna close this and continue in #16

**Comment by brandonmp** [comment] 2016-08-16 13:15
````
// package.json/npm start: 

"start": {
      "command": "babel-node bin/server",
      "env": {
        "DEBUG": "app:*"
      }
    },


// bin/server: 

import server from '../server/main'
...

const debug = _debug('app:bin:server')
const port = config.server_port
const host = config.server_host

server.listen(port)
````

**Closed by kenwheeler** 2016-08-16 13:15 UTC

**Comment by isaachinman** [comment] 2016-08-16 13:28
@kenwheeler I am not using nodemon in my project and I also encountered this.

**Comment by kenwheeler** [comment] 2016-08-16 13:28
@isaachinman how do you run your server?

**Comment by grgur** [comment] 2016-08-16 13:51
Not using nodemon either. 
I tested with this boilerplate and it happened too: https://github.com/erikras/react-redux-universal-hot-example

**Comment by isaachinman** [comment] 2016-08-16 13:52
@kenwheeler It's based loosely on [this boilerplate](https://github.com/erikras/react-redux-universal-hot-example) (the same that @grgur just linked). Just double-checked my `node_modules` dir for nodemon in case it was a sub-dependency - it's not.

**Comment by grgur** [comment] 2016-08-16 13:59
also @kenwheeler, since you asked about computer used - OS X 10.11.6, macbook pro, using the built in touchpad.

**Comment by isaachinman** [comment] 2016-08-20 14:07
@grgur Have you had any luck getting this setup with the erikras boilerplate?

**Comment by grgur** [comment] 2016-08-22 05:54
@isaachinman I haven't tried since, which sucks, but i'd love to contribute and i'll get back to you when i figure it out

**Comment by isaachinman** [comment] 2016-08-22 06:36
@grgur I will also re-attempt it this week sometime. Let me know if you have any success.

**Comment by isaachinman** [comment] 2016-10-11 11:38
@grgur Did you ever get this set up? Just tried again with the latest version v0.2.0, still can't get it working whatsoever with the erikras boilerplate: https://github.com/erikras/react-redux-universal-hot-example.
