### ISSUE TITLE
Mouse gesture brings random characters on screen - Ubuntu GNOME Terminal

### ISSUE THREAD

**Issue by lekhnath** [FormidableLabs/webpack-dashboard#54] opened 2016-08-17 17:43 UTC
I am on ubuntu os and using default terminal (GNOME Terminal). Whenever I do something with my mouse (click, move) over the dashboard it starts filling my terminal with random characters. 

`{quiet: true }` is there and `webpack.NoErrorsPlugin()` is also present.

Screenshot might help.

![webpack-dashboard-error](https://cloud.githubusercontent.com/assets/4231691/17746770/60e31268-64d1-11e6-95e9-c86a400c2d25.png)

**Comment by kenwheeler** [comment] 2016-08-17 18:27
closing as a duplicate of #16 , please try the branch in #50

**Closed by kenwheeler** 2016-08-17 18:27 UTC
