### ISSUE TITLE
incorrect layout of the `modules` section

### ISSUE THREAD

**Issue by neekey** [FormidableLabs/webpack-dashboard#175] opened 2017-06-28 04:04 UTC
> Please provide a description of the bug / issue, and provide the details below:

====================================================================

###### If the issue is visual, please provide screenshots here

![image](https://user-images.githubusercontent.com/499870/27620064-4fd562a6-5c0a-11e7-9ade-77e5adaa1665.png)

====================================================================

###### Steps to reproduce the problem

You don't need to do anything, it will just render this way
====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)

the command I was using: 

```
node node_modules/webpack-dashboard/bin/webpack-dashboard -- node node_modules/webpack-dev-server/bin/webpack-dev-server --host=0.0.0.0 --content-base=dist --hot --inline --watch --history-api-fallback
```

2. webpack.config.js

Just followed the instruction.

====================================================================

###### More Details

- What operating system are you on? OSX(10.11.6)
- What terminal application are you using? Terminal (2.6.1)
- What version of webpack-dashboard are you using? 0.4.0
- What is the output of running `echo $TERM`? `xterm-256color`

**Comment by jcarenza** [comment] 2017-08-17 16:05
I ran into this same issue when I added the ```webpack.optimize.ModuleConcatenationPlugin()```. Now, I'm seeing the same thing as @neekey 's screenshot.

If I remove this plugin, the formatting returns to normal. So, just add some logic to your config file that only adds it when you're not in HMR.

**Comment by ryan-roemer** [comment] 2017-10-11 15:08
We now have full support for `webpack.optimize.ModuleConcatenationPlugin()` and have several other fixes to.

Can either of you pull latest `webpack-dashboard` and `inspectpack` dependencies and check if anything is wrong?

If so, please open a "minimal error" repository with code to produce the error/bad behavior and install + reproduction steps. This will enable us to much more quickly figure out what the issue is. Thanks!

**Comment by ryan-roemer** [comment] 2017-10-13 13:24
Removing from `1.0` milestone until we have a reproduction / otherwise verify issue.

**Comment by ryan-roemer** [comment] 2017-10-18 12:48
Closing as we still don't have a reproduction. If this is still an issue in `^1.0.0` please do re-open with a "minimal error" repository for us to dig into and diagnose. Thanks!

**Closed by ryan-roemer** 2017-10-18 12:48 UTC
Labels: Bug, Unverified
