### ISSUE TITLE
Don't work with concurrently and nodemon

### ISSUE THREAD

**Issue by victorgarciaesgi** [FormidableLabs/webpack-dashboard#218] opened 2017-10-30 09:18 UTC
I can't make it work with webpack --watch and concurrently

```javascript
"scripts": {
    "dev": "concurrently --kill-others \"npm run clean && npm run server\" \"npm run dev-server\"",
    "server": "webpack-dashboard -- nodemon Server.js",
    "server-prod": "cross-env NODE_ENV=production nodemon Server.js",
    "dev-server": "webpack --watch --hot",
    "prod": "cross-env NODE_ENV=production npm run clean && npm run build-prod && npm run server-prod",
    "clean": "rimraf dist",
    "build-prod": "webpack --config config/webpack.config.prod.js --progress"
  },
```

**Comment by ryan-roemer** [comment] 2017-10-30 13:24
Can you please create a minimal repository with code + install + steps to reproduce the error so that we can see it too? Thanks!

**Comment by pranshu1992** [comment] 2017-11-07 07:42
I think there is an issue with concurrently. Works fine with nodemon for me when I run the first script. In the second script dashboard never shows up. 

"scripts": {
    "start": "webpack-dashboard -- nodemon server.js",
    "start-test-env": "concurrently \"gulp minify-css-dev\" \"webpack --config webpack_test.config.js\" \"export NODE_ENV=test && webpack-dashboard -- nodemon server.js\" 
}

**Comment by ryan-roemer** [comment] 2017-11-07 18:09
As already discovered in #214 (shelljs) and #217 (nodemon), some libraries are incompatible with `blessed`, the terminal magic library webpack-dashboard we use.

Can you apply a change like I've done in https://github.com/FormidableLabs/webpack-dashboard/issues/217#issuecomment-342570220 to remove webpack-dashboard completely and just run the simplest blessed sample to see if the issue is still there?

It would likely be something like:

```js
    "server": "nodemon node_modules/blessed/example/simple-form.js",
    "server-prod": "cross-env NODE_ENV=production nodemon node_modules/blessed/example/simple-form.js",
```

**Comment by nurishi** [comment] 2018-04-29 13:43
I ran into the same issue with concurrently, however, adding --raw param to concurrently did a trick for me.

```
  "scripts": {
    "start": "concurrently --raw --kill-others \"nw public\" \"npm run dev\"",
    "dev": "webpack-dashboard -- webpack-dev-server --mode development",
```

**Comment by ryan-roemer** [comment] 2018-05-24 21:35
Closing in lieu of https://github.com/FormidableLabs/webpack-dashboard/issues/223

**Closed by ryan-roemer** 2018-05-24 21:35 UTC
Labels: Unverified

**Comment by junjettrasmonte** [comment] 2020-05-16 05:14
added -- --watch instead of just --watch fixed it for me.
