### ISSUE TITLE
printing unexpected characters on terminal

### ISSUE THREAD

**Issue by raminious** [FormidableLabs/webpack-dashboard#53] opened 2016-08-17 17:37 UTC
When I move my mouse on terminal screen this characters will print on terminal
Is this bug or misconfiguration ?

os: Fedora 21
terminal: guake

![screenshot from 2016-08-17 22 03 33](https://cloud.githubusercontent.com/assets/334716/17746732/bcbfa386-64c6-11e6-882d-b73ffc03dedb.png)

**Comment by kenwheeler** [comment] 2016-08-17 17:39
closing as a dupe of #16 , try the branch in #50

**Closed by kenwheeler** 2016-08-17 17:39 UTC

**Comment by raminious** [comment] 2016-08-18 08:34
Not solved

webpack.compile

```js
const DashboardPlugin = require('webpack-dashboard/plugin');
const compiler = webpack(webpackConfig)
compiler.apply(new DashboardPlugin());
```

package.json

```
"dev": {
      "command": "webpack-dashboard -- nodemon --exec babel-node bin/server",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*"
      }
}
```
