### ISSUE TITLE
TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by Fandekasp** [FormidableLabs/webpack-dashboard#219] opened 2017-10-31 02:16 UTC
> Please provide a description of the bug / issue, and provide the details below:

I can start the webpack-dashboard and see the progress and logs appear, but once the progress reaches 100% and logs finish appearing, the dashboard crashes with the following traceback:
```
➜ yarn watch
  yarn run v1.2.1
  $ webpack-dashboard -- webpack --watch
  TypeError: Cannot read property 'slice' of null
      at /home/dori/Projects/work/aaa/node_modules/blessed/lib/program.js:2543:35
      at Array.forEach (<anonymous>)
      at Program._attr (/home/dori/Projects/work/aaa/node_modules/blessed/lib/program.js:2542:11)
      at Log.Element._parseTags (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/element.js:498:26)
      at Log.Element.parseContent (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/element.js:393:22)
      at Log.Element.setContent (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/element.js:335:8)
      at Log.Element.insertLine (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/element.js:2383:8)
      at Log.Element.pushLine (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/element.js:2526:15)
      at Log.log.Log.add (/home/dori/Projects/work/aaa/node_modules/blessed/lib/widgets/log.js:61:18)
      at Dashboard.setStats (/home/dori/Projects/work/aaa/node_modules/webpack-dashboard/dashboard/index.js:167:18)
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Related issue: #173 

====================================================================

###### Steps to reproduce the problem
Not sure, just tried installing webpack-dashboard in my existing and working project. Will investigate later if I find the time

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
```webpack-dashboard -- webpack --watch```
2. webpack.config.js
A bit too long, will have to remove irrelevant parts first
3. index.js (Your express based dev server, if applicable)
Just running the dist code on a docker nginx container, and executing `webpack --watch` separately

====================================================================

###### More Details

- What operating system are you on?  Arch Linux
- What terminal application are you using?  Termite & Tmux
- What version of webpack-dashboard are you using? 1.0.0
- What is the output of running `echo $TERM`? screen-256color

**Comment by ryan-roemer** [comment] 2017-11-07 18:40
@Fandekasp -- Can you create a minimal repository with installation + reproduction steps to see the issue so that we can jump in and more quickly diagnose the issue? Thanks!

**Comment by ryan-roemer** [comment] 2017-11-14 21:35
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!

**Closed by ryan-roemer** 2017-11-14 21:35 UTC
Labels: Unverified

**Comment by KevinLiuMapr** [comment] 2018-04-02 21:55
I ran into the exact issue and it seems to be because some other component of mine isn't allowing me to use js for..in or the output of that is causing an error

**Comment by ryan-roemer** [comment] 2018-04-02 22:40
@KevinLiuMapr -- Can you create a minimal github repository with install + error reproduction steps documented so we can jump in and see what's going on? Thanks!
