### ISSUE TITLE
[Idea] Web interface

### ISSUE THREAD

**Issue by cristian-sima** [FormidableLabs/webpack-dashboard#116] opened 2016-09-07 10:08 UTC
Hi. 

# Intro

`webpack-dashboard` is great. Why? Because it better structures the information into sections. You can see the process, the status, the modules, a history of them and so on...

# Problem(s)

I am using `Windows`. (and as I said other times I'm not enjoying it at all). On my pc, the dashboard is this:

![image](https://cloud.githubusercontent.com/assets/12199042/18307811/b062f522-74fa-11e6-86f9-0031268db426.png)

I scanned the issues of `webpack-dashboard` and I've seen that many of them relate to the visual content, which is (badly) displayed.

Another big problem is that of configuration. I've had a lot of problems trying to make it work

## Proposal 

We (the community) develop web projects. And we know how to do.

We can create a simple node server which listens to the `webpack-dev-server` and then displays the dashboard. Based on receiving events from the server, it displays the dashboard. 

Why not use the power of browser in order to display a dashboard in real time?

The project should be simple (I do not know the detailed implementation of this project).

## Why 

- no more cross-os styling problems
- easy to customize and add more features 
- may have a panel to change the configuration of `webpack` (think of changing the `devtool` from a select menu, rather than going to the code, edit the file, close the editor, stop `webpack` re-run it again
- may communicate with other `server(s)` such as [RHL ](https://github.com/gaearon/react-hot-loader) in order to see the progress of replacements (so you do not have to look every time at console)
- not blocking the console (because now `webpack-dashboard` is blocking the console
- may be other benefits

What do you think?

**Comment by kenwheeler** [comment] 2016-09-29 16:58
Alright, this is happening. Windows is way too much of a headache.

**Comment by kenwheeler** [comment] 2016-10-01 17:47
alright, work has begun on the web version, closing as a dupe of #120

**Closed by kenwheeler** 2016-10-01 17:47 UTC
Labels: Feature Request
