### ISSUE TITLE
[NOT BUG] `optionalDependencies` don't install on Windows.

### ISSUE THREAD

**Issue by iliran11** [FormidableLabs/webpack-dashboard#224] opened 2017-11-13 14:02 UTC
###### Enviroment

- What operating system are you on? `Microsoft Windows [Version 10.0.15063]`
- What terminal application are you using? `Windows PowerShell`
- What version of webpack-dashboard are you using? `latest`
- Node Version: `8.9.1`

When running `npm install webpack-dashboard --save-dev`  - installation failed with the following trace:

```
C:\personal\webpack-dashboard> npm install webpack-dashboard --save-dev

> integer@1.0.1 install C:\personal\webpack-dashboard\node_modules\integer
> node tools/install


C:\personal\webpack-dashboard\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\liranc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\personal\webpack-dashboard\node_modules\integer
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> farmhash@1.2.1 install C:\personal\webpack-dashboard\node_modules\farmhash
> node-gyp rebuild


C:\personal\webpack-dashboard\node_modules\farmhash>if not defined npm_config_node_gyp (node "C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\liranc\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\liranc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\personal\webpack-dashboard\node_modules\farmhash
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN webpack-test@1.0.0 No description
npm WARN webpack-test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.1 (node_modules\integer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.1 install: `node tools/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 (node_modules\farmhash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

====================================================================

###### Please provide a gist of relevant files

**package.json**

```json
{
  "name": "webpack-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "webpack": "^3.8.1",
    "webpack-dashboard": "^1.0.2",
    "webpack-dev-server": "^2.9.4"
  },
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  }
}
```
**webpack.config.js**

```javascript
var path = require('path');
// Import the plugin:
var DashboardPlugin = require('webpack-dashboard/plugin');

// If you aren't using express, add it to your webpack configs plugins section:
module.exports = {
    entry: './index.js',
    output: {
        filename: './bundle.js',
        path: path.resolve(__dirname)
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ["es2015", "react"]
                    }
                }
            }]
    },
    plugins: [
        new DashboardPlugin()
    ]
};
```

**index.js**

```javascript
ReactDOM.render(
    <h1>Hello, world!</h1>,
    document.getElementById('root')
  );
```

**index.html**
```html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>webpack dev server</title>
  <link rel="shortcut icon" href="">
</head>

<body>
  <div id="root"></div>
</body>
<script src="//unpkg.com/react/umd/react.development.js"></script>
<script src="//unpkg.com/react-dom/umd/react-dom.development.js"></script>
<script src="/bundle.js"></script>

</html>
```
====================================================================

**Comment by ryan-roemer** [comment] 2017-11-13 15:02
Looks like a duplicate of https://github.com/FormidableLabs/webpack-dashboard/issues/216

@iliran11 -- Did your installation actually fail to install `webpack-dashboard`? From the log you've posted, only the `optionalDependencies` failed to install (and that's OK by design on unsupported OSes).

If it actually failed to install, please create a minimal repository with install + reproduction steps and we'll jump in more.

**Comment by iliran11** [comment] 2017-11-13 15:36
Yes, it is installed and even actually seems to work.

**Comment by ryan-roemer** [comment] 2017-11-13 16:58
Cool.

**Closed by ryan-roemer** 2017-11-13 16:58 UTC

**Comment by ryan-roemer** [comment] 2018-04-17 19:16
@rajinehru -- I'm unclear as to how that would be a bug with this library. If your further diagnosis reveals that it is, please open a new ticket, with a full stack trace including where in `webpack-dashboard` you're hitting an error and a minimal public GitHub repository that includes installation and error reproduction steps so we can clone it down and see what you're seeing. Thanks!
