### ISSUE TITLE
Show how long build took and how long ago last build finished

### ISSUE THREAD

**Issue by DutchKev** [FormidableLabs/webpack-dashboard#37] opened 2016-08-16 12:08 UTC
* Feature Request

It would be nice to know how long the build took, to do some measurements.

And maybe also show how long ago the last build finished, just to get the confirmation everything went fine on the last build. The screen doesn't show any visual difference between 2 successful builds (if the file sizes are still the same etc of course).

**Comment by kenwheeler** [comment] 2016-08-16 12:49
Totes

**Comment by nickmask** [comment] 2016-08-17 00:03
Progress seems like a good place to have this. After the loading bar is done it remains empty.

**Comment by kenwheeler** [comment] 2016-08-18 01:24
I'm going to close this as a dupe of #24 and continue the discussion there

**Closed by kenwheeler** 2016-08-18 01:24 UTC
Labels: Feature Request
