### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tpickett** [FormidableLabs/webpack-dashboard#49] opened 2016-08-17 14:53 UTC
I cant seem to run the dashboard through docker/docker-compose. If i ssh into the container and start up the dev server it renders fine, but when i run it through docker-compose i get weird output. I believe it might be a buffer from the mouse movements in the terminal?
I cant copy paste the output.

Using Fish and terminator.

**Comment by kenwheeler** [comment] 2016-08-17 15:36
Can you try this branch https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by kenwheeler** [comment] 2016-08-18 01:22
This should be fixed in the latest release

**Closed by kenwheeler** 2016-08-18 01:22 UTC
Labels: Question

**Comment by tpickett** [comment] 2016-08-18 14:39
I get the same output with the new release "0.1.1" when i start it through docker-compose it only outputs the mouse positions.

**Comment by AnthonyTsang** [comment] 2016-08-22 14:42
@kenwheeler I do not think it can run with docker even for `0.1.6`.
I have gone through the code base and have some thought about how to deal with it.

1. One docker instance by design, should run only one process. We should separate `webpack-dashboard` out of the server instance.
2. We can only receive stdout from docker instance by `docker logs`. Therefore, running `webpack-dashboard` in any docker instance is not an option.
3. Docker host in some case may run in another machine with dedicated IP. For instance, running with `docker-machine` which will create a VM for docker instances.

Therefore, things to-do are 
1. Swap `socket.io` and `socket.io-client` so that the CLI can specify an IP (I am not familiar with socketIO. I guess there is no harm to do so.)
2. Add a parameter IP to  CLI.
3. As a result, we can run `webpack-dashboard --ip xxx.xxx.xxx.xxx --port xxx -- docker logs --follow CONTAINER` and it should work perfectly...

**Comment by crisu83** [comment] 2016-10-17 12:25
What's the current status of this issue?
